# Generated by Django 5.2.10 on 2026-01-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='slug',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
